export const userForm = (
  handleChangeOrganization,
  handleChangeOrganizationType,
  handleChangeIntersted,
  handleChangeUserPosition,
  handleChangeSenior,
  statusDetail,
  status,
  entities,
  interests,
  userDetails,
  organizationValue
) => {
  return [
    {
      name: "name",
      label: "fullName",
      type: "text",
      typeInput: "RHFTextField",
      loading: statusDetail === "succeeded",
      farsi: true,
    },
    {
      name: "mobile",
      label: "phoneNumber",
      type: "number",
      typeInput: "RHFTextField",
      loading: statusDetail === "succeeded",
    },
    {
      name: "email",
      label: "email",
      type: "text",
      typeInput: "RHFTextField",
      loading: statusDetail === "succeeded",
    },
    {
      name: "organization",
      label: "partOfOrganization",
      typeInput: "RHAuto",
      multiple: false,
      change: handleChangeOrganization,
      loadingCreate: true,
      loadingEdit: statusDetail === "succeeded" && status === "succeeded",
      propValue: "name",
      propTitle: "name",
      values: [
        { name: "شعبه" },
        { name: "ستاد" },
        { name: "شرکت های فرعی" },
        { name: "نمایندگان" },
        { name: "سایر" },
      ],
      async: false,
      value: {
        name: userDetails?.data?.user?.organization,
      },
    },

    {
      name: "organization_id",
      label: "partOfOrganization",
      typeInput: "RHAuto",
      change: handleChangeOrganizationType,
      propValue: "id",
      propTitle: "name",
      multiple: false,
      loadingCreate: status === "succeeded",
      loadingEdit: statusDetail === "succeeded" && status === "succeeded",
      values: entities?.data?.organizations ?? [],
      value: entities?.data?.organizations?.find(
        (e) => e.id === organizationValue
      ),
      async: true,
    },
    {
      name: "personnel_code",
      label: "personality code",
      type: "number",
      typeInput: "RHFTextField",
      loading: statusDetail === "succeeded",
    },
    {
      name: "interests",
      label: "intersted",
      typeInput: "RHAuto",
      change: handleChangeIntersted,
      loadingEdit: statusDetail === "succeeded" && status === "succeeded",
      loadingCreate: status === "succeeded",
      multiple: true,
      async: true,
      values: entities?.data?.interests ?? [],
      value: interests ?? [],
      propValue: "id",
      propTitle: "title",
    },
    {
      name: "position",
      label: "position",
      type: "text",
      typeInput: "RHFTextField",
      loading: statusDetail === "succeeded",
    },

    {
      name: "level",
      label: "userPosition",
      change: handleChangeUserPosition,
      loadingCreate: status === "succeeded",
      loadingEdit: statusDetail === "succeeded" && status === "succeeded",
      typeInput: "RHAuto",
      propValue: "name",
      propTitle: "name",
      onInputChange: undefined,
      multiple: false,
      values: [
        { name: "RM5" },
        { name: "RM6" },
        { name: "RM7" },
        { name: "RM4" },
        { name: "RM3" },
        { name: "RM2" },
        { name: "RM1" },
      ],
      async: false,
      value: {
        name: userDetails?.data?.user?.level,
      },
    },
    {
      name: "parent_id",
      label: "directSeniorUser",
      change: handleChangeSenior,
      propValue: "id",
      propTitle: "name",
      loadingCreate: status === "succeeded",
      loadingEdit: statusDetail === "succeeded" && status === "succeeded",
      onInputChange: undefined,
      values: entities?.data?.users ?? [],
      typeInput: "RHAuto",
      multiple: false,
      async: true,
      value: entities?.data?.users?.find(
        (e) => e.id === userDetails?.data?.user?.parent_id
      ),
    },
  ];
};
